### PR TITLE
[SERV-1060] Update curl version

### PR DESCRIPTION
**Pull request by angelahuqing**

### CODE REVIEW

**Comment by gpetz** [comment]
just update to Grok 12.0.0 to fix the problem, the old version 11.0.0 is no longer available

**Comment by ksclarke** [comment]
@gpetz Yes, that's the plan. It's a bit odd, though, that that repo was totally reset and all past releases removed. Since it's also a major version bump, we're doing due diligence on it before just folding it in.

We are aware that this was originally a curl issue and around three days ago also became a grok issue, too, though, thanks.

**Comment by ksclarke** [comment]
Will just update here since the ticket for this work is in our local Jira instead of the GitHub Issues queue. We're going to remove Grok and go back to using OpenJPEG in the container. I've created a new ticket for this in our local Jira. The lack of transparency in the Grok project is concerning and makes us think OpenJPEG, which is more established and has more committers, will be the safer choice.

**Comment by ksclarke** [comment]
@angelahuqing Let's just go ahead and close this PR and we'll fold the curl update into the larger Grok -> OpenJPEG swap.

**Pull request closed without merging**
