### PR TITLE
[SERV-332] Add auth-http-401.patch build to GHA release workflow

### PR DESCRIPTION
**Pull request by markmatney**
So that we can publish images that use the patch in an automated way.

Also updates the auth-http-401.patch to properly handle image responses.

### CODE REVIEW

**Review by DRickard — DISMISSED** [review]

**Review by ksclarke — COMMENTED** [review]
Is there a reason to have our nightly build not use this patch?

**Comment by markmatney** [comment]
Hmm, just to step back a bit: what about calling the patched image a pre-release version instead? It's not been as thoroughly tested as I think is required to justify us presenting it as production-ready -- yet. (So, perhaps neither the nightly build nor the release build should include it -- yet.)

**Comment by ksclarke** [comment]
I don't think we make any promises about the nightly build being a production-ready build. It's a snapshot of our work in progress (and used to catch, in theory, needed OS dependency updates). We could add it there and not add it to the tagged build (yet)?

**Comment by markmatney** [comment]
Not sure why the PR builds are hanging, but I've added the patch to the nightly build (and not to the tagged one).

**Review by DRickard — DISMISSED** [review]

**Review by ksclarke — APPROVED** [review]

**Review by DRickard — APPROVED** [review]

**Pull request merged**
